input {
  syslog { port => 5514 }
}

filter {
  grok {
    match => { "message" => "%{SYSLOGTIMESTAMP:ts} %{HOSTNAME:host} %{WORD:program}: %{GREEDYDATA:body}" }
  }
  date {
    match => ["ts", "MMM dd HH:mm:ss"]
    target => "@timestamp"
  }
}

output {
  elasticsearch { index => "web-shop-logs-%{+YYYY.MM.dd}" }
}
